services:
  rustdesk-server:
    image: rustdesk/rustdesk-server-s6:latest
    container_name: rustdesk-server
    environment:
      RELAY: ${RELAY}
      ALWAYS_USE_RELAY: ${ALWAYS_USE_RELAY:-N}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21117:21117"
      - "21118:21118"
      - "21119:21119"
    volumes:
      - ./data:/data
    restart: unless-stopped
